version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: desapp-normalized
    ports:
      - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "npm", "run", "start:docker" ]
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: devuser
      DB_PASSWORD: devpass
      DB_NAME: desapp-normalized
    ports:
      - "3001:3001"
    depends_on:
      - db
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
        - db
    volumes:
      -  pgadmin_data:/var/lib/pgadmin # <— persistencia de la configuración de pgAdmin

volumes:
  db_data:
  pgadmin_data: