version: '3.9'

services:
  db:
    image: postgres:16
    container_name: desapp_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desapp_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: desapp_api
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: desapp_db
      DB_SSL: false
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run seed && npm run start:dev"

volumes:
  postgres_data:
